### ISSUE TITLE
Windows: sync stops at 99%+ > node is disconnected 

### ISSUE THREAD

**Issue by rene-sch** [DeFiCh/app#325]
### Preflight Checklist

- [rene-sch ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [rene-sch] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  -  2.1.10
- **Previous DeFi App Version:**
  -  2.1.3
- **Operating System (OS):**
  -  Windows 10

### Actual Behavior
 
I wanted to update the app from version 2.1.3 to 2.1.10.
After the synchronization was at 98.89% the error came: "Connection to the node disconnected"

Then I increased the swap file on my Windows 10 (12 GB RAM). After that I tried several times but always at 98.89% the message Connection to the node was disconnected

### Expected Behavior

I expected the app to work properly after installation

### App log / binary log / app config

[LogData.zip](https://github.com/DeFiCh/app/files/5826804/LogData.zip)

**Comment by rene-sch** [comment]
attached a screenshot
![Wallet - DeFi app 17 01 2021 22_05_22](https://user-images.githubusercontent.com/77586771/104856094-cbe40800-5910-11eb-95ff-dcd57b1514b0.png)

**Comment by rene-sch** [comment]
Note: I had the same problem with the update from 2.1.3 to 2.1.9

**Comment by rene-sch** [comment]
Here are the right logs, sorry for that
[App Config.zip](https://github.com/DeFiCh/app/files/5826880/App.Config.zip)

**Comment by maaze19** [comment]
For me it works with every systems when I do it the following:
1. Start the defid.exe without the app
```
Open cmd and type
.\defid.exe -conf="%USERPROFILE%\.defi\defid.conf"
```
2. Observe the RAM consumption of the app in the taskmanager. When it exceeds 1 GB (with your amount of RAM, you can wait until it exceeds 2GB - 4GB) select the cmd window and press `Ctrl + C` to shutdown the node. **Do not close the cmd window with "X", the blockchain can be corrupted**
3. Wait until you can enter the next command and start from step 1. Check whether it syncs from your last synced block number.

**Remember you need to start it with the parameter `-reindex` the first time ( `.\defid.exe -conf="%USERPROFILE%\.defi\defid.conf" -reindex` )** like described in the release notes.

**Why it helps?**
defid.exe will need about 300 MB of RAM when you restart the process, but can already use the last blockchain state. Then it will increase again (I could see increasing it to almost 14GB RAM usage without any restart). The first 500.000 blocks can be synced without problems, then you will have to restart the sync process more often.

**Comment by izzycsy** [comment]
Hi @rene-sch , thanks for your feedback. Please give us time to investigate this issue. Thank you.

**Comment by BenThrottle85** [comment]
Hi everyone,

I have the same problem with 2.1.10.
Maybe it's important to point out that this message appears when the synchronisation is almost finished.

**Comment by izzycsy** [comment]
Hi @BenThrottle85 , thanks for your feedback. This error occur because there's a potential bug, not because synchronisation is almost complete. The expected behaviour should be that it syncs to 100% with no error. Could you send your logs please?

**Comment by BenThrottle85** [comment]
Of course...

[AppLogs.zip](https://github.com/DeFiCh/app/files/5843062/AppLogs.zip)
[BinaryLogs.zip](https://github.com/DeFiCh/app/files/5843063/BinaryLogs.zip)

**Comment by izzycsy** [comment]
Hi @BenThrottle85 , well received, please give us time to investigate. Thank you.

**Comment by kingsersch** [comment]
I have the same problem with 2.1.10.

[App Logs.zip](https://github.com/DeFiCh/app/files/5845098/App.Logs.zip)
[App Config.zip](https://github.com/DeFiCh/app/files/5845101/App.Config.zip)

**Comment by kingsersch** [comment]
![bandicam 2021-01-20 20-52-53-252](https://user-images.githubusercontent.com/77615565/105230696-0a263500-5b66-11eb-9152-0030f06f7770.jpg)

**Comment by izzycsy** [comment]
Hi @kingsersch , well received. The team is currently investigating this issue.

**Comment by FrostyEraser** [comment]
Hello,

so i had the same problem on windows since 2.1.6. i think.
The connection to node stuff or the app only showing a white screen.

Two or three times it helped to delete the folder "C:\Users\YOUR_USERNAME\AppData\Roaming\DeFi Blockchain".

With 2.1.9 i was not able to get the App running again. I deleted every folder with defi stuff, but not working.

My solution now is, i have the wallet app running permanently on a virtual machine with linux mint.

Running like a charm, i had a power shortout once. And the NAS with the VM failed.

Then again the Node shit was not connecting. So restored the last Snapshot from 2 days before.
App synced without problems. 

Setting up a VM on a Windows PC is not a problem for someone that can google and it seems the linux version is not so buggy.

Please Team before you add any features or whatever debug that damn App.

Nevertheless DFI is great!!!

Love you guys :-D

**Comment by TTSIP** [comment]
I had the samel isse and for me it was simply the hardware space had 12 GB free but this was not enough i have now 150 GB and now it works

**Comment by bvbfan** [comment]
@maaze19 i agree that restarting node will fix some higher ram usage, which version you use? I can't see more than 1 GiB in use during sync?

**Comment by thiencdam** [comment]
Same issue synchronizing with 2.1.11 update.

![image](https://user-images.githubusercontent.com/77680154/105609560-6310eb80-5d67-11eb-8924-105d270e6eac.png)


[Apps-log.zip](https://github.com/DeFiCh/app/files/5860658/Apps-log.zip)

**Comment by bvbfan** [comment]
How much memory you have?

**Comment by thiencdam** [comment]
8G of RAM, 312G disk space.

**Comment by bvbfan** [comment]
Can you confirm that you have a bit more wallet addresses ?

**Comment by thiencdam** [comment]
This was my wallet address in the version 2.1.10. I could not get past the synchronization issue in version 2.1.11 to see my wallet.
![image](https://user-images.githubusercontent.com/77680154/105639574-5f986580-5e36-11eb-8dd6-9090f51e504a.png)

**Comment by thiencdam** [comment]
I updated to 2.1.12, but the issue still not resolved. Can't view my wallet, can't do anything.
[App_logs.zip](https://github.com/DeFiCh/app/files/5862908/App_logs.zip)
![2_1_12 DEFI node](https://user-images.githubusercontent.com/77680154/105639788-61165d80-5e37-11eb-8877-c31829772ae8.JPG)

**Comment by bvbfan** [comment]
@thiencdam can provide screenshot with open task manager around 580k block how much memory is used? From the logs you don't have enough memory.

**Comment by FrostyEraser** [comment]
I had the same problem and i have 32 Gb of Ram, so in my opinion there is a bug that causes the ram to run out. 
Not the other way round.
Right now it's running smootly in an Linux VM with 4 GB Ram, no problems so far.

**Comment by thiencdam** [comment]
Here is the snap shot, with task manager, where synchronizing stalled.
![Capture](https://user-images.githubusercontent.com/77680154/105916723-a335cf80-5fee-11eb-8f5c-acd6b441616d.JPG)

**Comment by thiencdam** [comment]
Updated to 2.1.13 on Windows 10. No improvement. Synchronizing stalled at block 591203. 

[App_binary.zip](https://github.com/DeFiCh/app/files/5877586/App_binary.zip)

![Capture1](https://user-images.githubusercontent.com/77680154/105939239-0ab34580-6016-11eb-8a47-58adf3be5e0c.JPG)
![Capture](https://user-images.githubusercontent.com/77680154/105939254-1272ea00-6016-11eb-8d70-7f6c7c2ed655.JPG)

**Comment by izzycsy** [comment]
Hi @rene-sch @BenThrottle85 @kingsersch @FrostyEraser can I check that you've updated to [v2.1.13](https://defichain.com/downloads/)? Please send new information (include screenshots) and app logs. Thank you. 

Hi @thiencdam well received, please give us time to investigate the issue.

**Comment by dieterich-m** [comment]
Link to #372 and #352

**Comment by goldi147** [comment]
same issue with Windows 8.1 and  V 2.1.13- see logs attached
[DEFI-Chain.zip](https://github.com/DeFiCh/app/files/5881031/DEFI-Chain.zip)

![image](https://user-images.githubusercontent.com/76776017/106010040-523edd80-60b9-11eb-824f-d20fc236e835.png)

**Comment by kingsersch** [comment]
![bandicam 2021-01-27 18-01-31-975](https://user-images.githubusercontent.com/77615565/106026545-3a238a00-60ca-11eb-90d8-aff0a5574bdd.jpg)

**Comment by bvbfan** [comment]
@goldi147  it's needed at least 1GiB of RAM to run node.
@thiencdam did you disable pagefile (swap) or virtual memory?

**Comment by goldi147** [comment]
Maybe I ran out of memory, but 4,6 gb is a huge number?

Is it better to install an older version? All my friends also have problems with 2.1.13.
If so please sen last stabil exe as link.

I also tried to run it in the cmd box in batches. After hours I got synchron, but after the next restart database (or synonym) has been corrupt. Now I try the Sync via programm again. It is running for 3-4 hours now.

Many thanks for your help!

[cid:image001.png@01D6F576.E9385EE0]

Von: Anthony Fieroni <notifications@github.com>
Gesendet: Donnerstag, 28. Jänner 2021 08:53
An: DeFiCh/app <app@noreply.github.com>
Cc: Mario Gold <Mario.Gold@anna-gold.at>; Mention <mention@noreply.github.com>
Betreff: Re: [DeFiCh/app] Windows: sync stops at 99%+ > node is disconnected (#325)


@goldi147<https://github.com/goldi147> it's needed at least 1GiB of RAM to run node.
@thiencdam<https://github.com/thiencdam> did you disable pagefile (swap) or virtual memory?

**Comment by goldi147** [comment]
I switched to V2.1.8 and got synchronised. But now when I try the add liquidity I get following massage:

[cid:image001.png@01D6F5AF.F9323F30]

Attached you find my logs as well.

Von: Anthony Fieroni <notifications@github.com>
Gesendet: Donnerstag, 28. Januar 2021 08:53
An: DeFiCh/app <app@noreply.github.com>
Cc: Mario Gold <Mario.Gold@anna-gold.at>; Mention <mention@noreply.github.com>
Betreff: Re: [DeFiCh/app] Windows: sync stops at 99%+ > node is disconnected (#325)


@goldi147<https://github.com/goldi147> it's needed at least 1GiB of RAM to run node.
@thiencdam<https://github.com/thiencdam> did you disable pagefile (swap) or virtual memory?

**Comment by thiencdam** [comment]
I did not disable pagefile (swap) or virtual memory. Yesterday, I uninstalled DefiApp and increased virtual memory to 32Gb, then reinstalled V2.1.13.  I don't know which step fixed it but it get synched and is now running beautifully.  I backed-up my wallet just in case. It did take a while to synchronize around block 591248.
![image](https://user-images.githubusercontent.com/77680154/106287519-1e240380-6204-11eb-84dc-e6acdc3c9a4b.png)

Good luck to everyone.

**Comment by thiencdam** [comment]
One thing I forgot to mention, I did restart the computer to clear the registry before reinstalling the app.

**Comment by goldi147** [comment]
when I sync via cmd: 
cd "%localappdata%\Programs\defi-app\resources\binary\win"
.\defid.exe -conf="%USERPROFILE%\.defi\defid.conf"
and stop with "ctrl+c" when I ran out of 4 gb memory I get synchonized.
but after the first or second restart I get errors again.

**Comment by jibesmaster** [comment]
I reindexed 4 times no improvement. I am stuck. How to fix it. It just stops at 99% and says node disconnected.

**Comment by izzycsy** [comment]
Hi @rene-sch @BenThrottle85 @kingsersch @goldi147 @jibesmaster , update [v2.1.15](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, kindly send new information (include screenshots) and app logs. Thank you.

**Comment by Ausafari** [comment]
Node disconnected issue continues to occur unabated.
Logs attached as requested, as is confirmatory screenshot.
[binary_log.log](https://github.com/DeFiCh/app/files/5899110/binary_log.log)
[app_log.log](https://github.com/DeFiCh/app/files/5899111/app_log.log)
![defi-app-fails-again](https://user-images.githubusercontent.com/75756887/106373336-46f2f700-63c4-11eb-91da-80fde995a419.jpg)

**Comment by UserMaxL** [comment]
Hi @izzycsy 
I updated from Version 2.1.13 to 2.1.15 and got a "Error: Corrupted block database detected" as described in #390 . During the following synchronizing I get the issue described above. I retried  3 times already and will keep doing it. Please find Log files and screenshot attached.
![Node Disco](https://user-images.githubusercontent.com/75398355/106375467-8d2c6400-638c-11eb-9b80-ea852b7b2e36.JPG)
[NodeDiscoLogs.zip](https://github.com/DeFiCh/app/files/5899222/NodeDiscoLogs.zip)

**Comment by UserMaxL** [comment]
@izzycsy 
After several tries (lazy Sunday) I found a solution for me:
The procedure is similar to the one from user maaze19 without the use of cmd. I have a 16 GB RAM machine with SSD and 2x2,4 GHz CPUs and version is 2.1.15. While synchronizing I monitored the RAM and closed the app when 4 GB or 45-50% of total RAM usage was reached.. I had to do this two times and synchronizing started with the blocks from previous closing and lower RAM usage. Now I'm fully synchronized and all works fine so far.

**Comment by izzycsy** [comment]
Hi @Ausafari , well received, please give us time to investigate this issue. Do you have screenshot of your Activity Monitor? 

<img width="734" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/106380770-576c9700-63ef-11eb-9858-f89742acf94c.png">

**Comment by Ausafari** [comment]
I use a PC, not a Mac, so the Activity Monitor doesn't provide the information a Mac does. However I can take a screenshot of Task Manager, if that will help? I am assuming you want such a screenshot from when the error occurs?

**Comment by izzycsy** [comment]
Hi @Ausafari , yes for windows PC it's your task manager.

**Comment by Ausafari** [comment]
OK, but you didn't answer as to when you want the screenshot taken, as asked previously. Is it when the app is trying to sync or when the app fails to sync?

**Comment by Ausafari** [comment]
The app failed again with the "Node is disconnected" error being thrown again before I received an answer from you @izzycsy . There's no point sending you the Task Manager output at this time as it's showing zero activity from the defi app of course.

**Comment by zyr2783** [comment]
Hi guys, I was facing the same issue (Node is disconnected). Then I removed all files and folders in the folder DeFi Blockchain. Now the problem is solved, my wallet is synchronized (at block 611616), but I lost my balance of DFI coins. What should I do in order to see my previous balance, please? Thanks in advance!

**Comment by BenThrottle85** [comment]
> Hi guys, I was facing the same issue (Node is disconnected). Then I removed all files and folders in the folder DeFi Blockchain. Now the problem is solved, my wallet is synchronized (at block 611616), but I lost my balance of DFI coins. What should I do in order to see my previous balance, please? Thanks in advance!

Have you restored your wallet with your seed phrase?

**Comment by zyr2783** [comment]
> 
> 
> > Hi guys, I was facing the same issue (Node is disconnected). Then I removed all files and folders in the folder DeFi Blockchain. Now the problem is solved, my wallet is synchronized (at block 611616), but I lost my balance of DFI coins. What should I do in order to see my previous balance, please? Thanks in advance!
> 
> Have you restored your wallet with your seed phrase?

No, I didn`t, how should I do that?

**Comment by BenThrottle85** [comment]
After reindexing still the same error "Node is disconnected"
Now I try to delete the .defi folder.

**Comment by BenThrottle85** [comment]
> > > Hi guys, I was facing the same issue (Node is disconnected). Then I removed all files and folders in the folder DeFi Blockchain. Now the problem is solved, my wallet is synchronized (at block 611616), but I lost my balance of DFI coins. What should I do in order to see my previous balance, please? Thanks in advance!
> > 
> > 
> > Have you restored your wallet with your seed phrase?
> 
> No, I didn`t, how should I do that?

Maybe you can upload a screenshot from your current screen?!
Have you made a backup of your wallet?

**Comment by rezaghiasi** [comment]
hi there, I am facing the same issue. 
I'm using macbook and version 2.1.15 of DeFi Chain app 
It syncs up to over 99% then it gives the error
How can I fix it?

**Comment by Ausafari** [comment]
Hi @izzycsy . I have attached two screenshots for you of the Task Manager output when the app fails. Each shows the different failure notices down the bottom right hand corner. From Task Manager you can see the system resources are not overloaded - the app simply fails - each and every time.

![defi-app-wallet-balance-failure](https://user-images.githubusercontent.com/75756887/106396661-258e1b80-6455-11eb-8dd1-4bde0caa9275.jpg)
![defi-app-wallet-balance-failure-network-error](https://user-images.githubusercontent.com/75756887/106396664-26bf4880-6455-11eb-8436-bbc82a38797b.jpg)

**Comment by BenThrottle85** [comment]
> hi there, I am facing the same issue. 
> 
> I'm using macbook and version 2.1.15 of DeFi Chain app 
> 
> It syncs up to over 99% then it gives the error
> 
> How can I fix it?

Update or fresh install?

**Comment by Ausafari** [comment]
I (and I suspect others in this thread) @BenThrottle85 have tried both methods numerous times - all without success. :(

**Comment by zyr2783** [comment]
> 
> 
> > > > Hi guys, I was facing the same issue (Node is disconnected). Then I removed all files and folders in the folder DeFi Blockchain. Now the problem is solved, my wallet is synchronized (at block 611616), but I lost my balance of DFI coins. What should I do in order to see my previous balance, please? Thanks in advance!
> > > 
> > > 
> > > Have you restored your wallet with your seed phrase?
> > 
> > 
> > No, I didn`t, how should I do that?
> 
> Maybe you can upload a screenshot from your current screen?!
> Have you made a backup of your wallet?

I have made a backup of my wallet, but unfortunately I cannot find the file.. But I have my recovery phase.. I`m 100% synchronized now, how can I get back my coins? I`m sure, I can find the address where I sent a coins from exchange. Does it help?

**Comment by rezaghiasi** [comment]
I have just found a solution and it worked, it might not be an efficient one but I think for those whom are worried about their funds it can be a solution 
I opened the app and once the percentage was going up I closed the app then open again for syncing, it took me a while more to finish the process but it did sync.

**Comment by Ausafari** [comment]
I have built on the work @UserMaxL did earlier and seem to have found a reliable method of making this app (the most unreliable DeFI app it has EVER been my sorry misfortune to use) sync.
1: Note the approximate block the app reaches when it throws the "Node disconnected" error (still occurring for all of we poor unfortunates after 6 days! Hang your heads in shame, app devs!)
2:  Launch the app.
3: Monitor it as it approaches the previous failure point. The block periods seem to oscillate around an (approximately) 20 second cycle.
4: As soon as you notice the block count stop advancing (give it say 30 seconds, just to be sure), close the app out. DO NOT wait for the app to fail.
5: Wait for the app to close completely before proceeding.
6: Relaunch the app - it may take a few minutes to relaunch, but be patient. Once it does relaunch, it should start again near or at the block where it left off.
7: Repeat steps 4-6 as necessary. (I had to close and re-launch the app three times before it finally synced).
8: When the app finally syncs, give a great big sigh of relief and continue on with the tasks you should reasonably have expected to be able  to have completed 6 DAYS AGO!!!!

**Comment by zyr2783** [comment]
OK, so my issue is solved. I have removed the app and deleted both folders (DeFi Blockchain and defi-app). Installed a newest version 2.1.15, wait for synchronizing and recovered with my seed phrase. All works! Thanks for your help.

**Comment by BenThrottle85** [comment]
I deleted the ".defi" folder on my Lubuntu VM:
1. syncing starts --> 100% with no problems. used memory was about 500MB all the time but it was much slower than the last times. but that's not the problem
2. app shows me my wallets but no coins displayed. but how does the app know what coins i had? i deleted the ".defi" folder!
3. Wallet -> Reset Wallet -> entered my seed phrase -> restoring wallet. my coins are back
4. opened DFI wallet -> "Include rewards" -> no rewards shown :-(
5. Reindexing ==> same issue again. the used memoy at about 90% goes up to the air.

I'm really frustrated right now!!!

**Comment by BenThrottle85** [comment]
> OK, so my issue is solved. I have removed the app and deleted both folders (DeFi Blockchain and defi-app). Installed a newest version 2.1.15, wait for synchronizing and recovered with my seed phrase. All works! Thanks for your help.

Can you see your rewards in the dfi wallet?

**Comment by zyr2783** [comment]
> 
> 
> > OK, so my issue is solved. I have removed the app and deleted both folders (DeFi Blockchain and defi-app). Installed a newest version 2.1.15, wait for synchronizing and recovered with my seed phrase. All works! Thanks for your help.
> 
> Can you see your rewards in the dfi wallet?

Yes, I can.

**Comment by rene-sch** [comment]
> For me it works with every systems when I do it the following:
> 
> 1. Start the defid.exe without the app
> 
> ```
> Open cmd and type
> cd "%localappdata%\Programs\defi-app\resources\binary\win"
> .\defid.exe -conf="%USERPROFILE%\.defi\defid.conf"
> ```
> 
> 1. Observe the RAM consumption of the app in the taskmanager. When it exceeds 1 GB (with your amount of RAM, you can wait until it exceeds 2GB - 4GB) select the cmd window and press `Ctrl + C` to shutdown the node. **Do not close the cmd window with "X", the blockchain can be corrupted**
> 2. Wait until you can enter the next command and start from step 1. Check whether it syncs from your last synced block number.
> 
> **Remember you need to start it with the parameter `-reindex` the first time ( `.\defid.exe -conf="%USERPROFILE%\.defi\defid.conf" -reindex` )** like described in the release notes.
> 
> **Why it helps?**
> defid.exe will need about 300 MB of RAM when you restart the process, but can already use the last blockchain state. Then it will increase again (I could see increasing it to almost 14GB RAM usage without any restart). The first 500.000 blocks can be synced without problems, then you will have to restart the sync process more often.



> Hi @rene-sch @BenThrottle85 @kingsersch @FrostyEraser can I check that you've updated to [v2.1.13](https://defichain.com/downloads/)? Please send new information (include screenshots) and app logs. Thank you.
> 
> Hi @thiencdam well received, please give us time to investigate the issue.


sorry for my late reply but i'm recovering from corona.

I still have problems finding the passage as described by maaze19 "Remember you need to start it with the parameter -reindex the first time (. \ defid.exe -conf ="% USERPROFILE% \. defi \ defid.conf "-reindex ) like described in the release notes. "

I would then go through the path he described

**Comment by UserMaxL** [comment]
@rene-sch 
Try my procedure - I didn't fully get the maaze19 description, but I tried something similar: 
While synchronizing I monitored the RAM usage in the Task Manager and closed the app when 4 GB or 45-50% of total RAM usage was reached ( I have a 16 GB RAM machine with SSD and 2x2,4 GHz CPUs and version is 2.1.15.). I had to do this two times and synchronizing started with the blocks from previous closing and lower RAM usage. It fully synchronized and all works fine so far.

**Comment by rene-sch** [comment]
@UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0. 
Do you close the app normally with "X"? and do you restart by double-clicking?

**Comment by BenThrottle85** [comment]
> I deleted the ".defi" folder on my Lubuntu VM:
> 
> 1. syncing starts --> 100% with no problems. used memory was about 500MB all the time but it was much slower than the last times. but that's not the problem
> 2. app shows me my wallets but no coins displayed. but how does the app know what coins i had? i deleted the ".defi" folder!
> 3. Wallet -> Reset Wallet -> entered my seed phrase -> restoring wallet. my coins are back
> 4. opened DFI wallet -> "Include rewards" -> no rewards shown :-(
> 5. Reindexing ==> same issue again. the used memoy at about 90% goes up to the air.
> 
> I'm really frustrated right now!!!

I created a new Virtual Machine and installed a fresh copy of the Defichain-App 2.1.15.
The Virtual Machine only has 4GB RAM but synchronisation works without any issues.

**Comment by UserMaxL** [comment]
> @UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0.
> Do you close the app normally with "X"? and do you restart by double-clicking?

Hi @rene-sch , yes, I just closed with "X" and opened with double click. Sorry it didn't work for you, but strange it starts at zero.

**Comment by rene-sch** [comment]
> > @UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0.
> > Do you close the app normally with "X"? and do you restart by double-clicking?
> 
> Hi @rene-sch , yes, I just closed with "X" and opened with double click. Sorry it didn't work for you, but strange it starts at zero.
Hi @UserMaxL do you always wait until the background processes of the app are closed before restarting it?

**Comment by UserMaxL** [comment]
> > > @UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0.
> > > Do you close the app normally with "X"? and do you restart by double-clicking?
> > 
> > 
> > Hi @rene-sch , yes, I just closed with "X" and opened with double click. Sorry it didn't work for you, but strange it starts at zero.
> > Hi @UserMaxL do you always wait until the background processes of the app are closed before restarting it?
Hi, yes, you should always wait until the background processes of the app are closed.

**Comment by rene-sch** [comment]
> > > > @UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0.
> > > > Do you close the app normally with "X"? and do you restart by double-clicking?
> > > 
> > > 
> > > Hi @rene-sch , yes, I just closed with "X" and opened with double click. Sorry it didn't work for you, but strange it starts at zero.
> > > Hi @UserMaxL do you always wait until the background processes of the app are closed before restarting it?
> > > Hi, yes, you should always wait until the background processes of the app are closed.

@UserMaxL okay now it seems to be working. Does the synchronization then start exactly at the % at which you closed the app?

**Comment by UserMaxL** [comment]
> > > > > @UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0.
> > > > > Do you close the app normally with "X"? and do you restart by double-clicking?
> > > > 
> > > > 
> > > > Hi @rene-sch , yes, I just closed with "X" and opened with double click. Sorry it didn't work for you, but strange it starts at zero.
> > > > Hi @UserMaxL do you always wait until the background processes of the app are closed before restarting it?
> > > > Hi, yes, you should always wait until the background processes of the app are closed.
> 
> @UserMaxL okay now it seems to be working. Does the synchronization then start exactly at the % at which you closed the app?

Yes, was the case for me...what version of the app are you using?

**Comment by rene-sch** [comment]
> > > > > > @UserMaxL Thank you for your quick response. I've tried your approach. but when I close the app the synchronization starts at 0.
> > > > > > Do you close the app normally with "X"? and do you restart by double-clicking?
> > > > > 
> > > > > 
> > > > > Hi @rene-sch , yes, I just closed with "X" and opened with double click. Sorry it didn't work for you, but strange it starts at zero.
> > > > > Hi @UserMaxL do you always wait until the background processes of the app are closed before restarting it?
> > > > > Hi, yes, you should always wait until the background processes of the app are closed.
> > 
> > 
> > @UserMaxL okay now it seems to be working. Does the synchronization then start exactly at the % at which you closed the app?
> 
> Yes, was the case for me...what version of the app are you using?

I'm currently trying to install version 2.1.16 from 2.1.6

**Comment by bvbfan** [comment]
Can you see in `C:\Users\Username\AppData\Roaming\DeFi\blocks` what's the size of first `blkXXXXX.dat`?

**Comment by bvbfan** [comment]
PS: You can't use older version, not because it's not recommended, you just can't.

**Comment by rene-sch** [comment]
> PS: You can't use older version, not because it's not recommended, you just can't.



@bvbfan the problem is that currently no version works. So I'm trying to install version 2.1.16.

**Comment by bvbfan** [comment]
They work it's related to `-reindex` can you check `C:\Users\Username\AppData\Roaming\DeFi\blocks` and write here which are the size of of top 3 items?

**Comment by rene-sch** [comment]
> They work it's related to `-reindex` can you check `C:\Users\Username\AppData\Roaming\DeFi\blocks` and write here which are the size of of top 3 items?

@bvbfan Do you mean these?
![Screenshot (47)](https://user-images.githubusercontent.com/77586771/107541677-ae305880-6bc7-11eb-85f0-0307de3838b9.png)

**Comment by bvbfan** [comment]
Delete only 3 blk file (first 3 after folder index) restart the app.

**Comment by rene-sch** [comment]
> Delete only 3 blk file (first 3 after folder index) restart the app.

normal with double click or should I download it again from github?

**Comment by bvbfan** [comment]
Latest version 2.17, just start it.

**Comment by rene-sch** [comment]
okay i'm trying. thank you

**Comment by rene-sch** [comment]
> Latest version 2.17, just start it.

@bvbfan 
I finally managed to synchronize version 2.1.17. Then I went to "restore wallet" but now no coins etc. are displayed. Do I have to restore the wallet with my seed?
Thanks for your endless help.

**Comment by monnyfx** [comment]
I got the 2.1.17 windows version but still same issue. my wallet is not loading node disconected.

**Comment by rene-sch** [comment]
Now everything is working again. I installed version 2.1.17 (like @bvbfan told me) and entered my seed. Everything back. Many thanks for your help

**Comment by izzycsy** [comment]
Hi @BenThrottle85 @kingsersch @TTSIP @thiencdam @goldi147 @jibesmaster @Ausafari @monnyfx , thank you for your patience on this issue. Can you try installing the latest [v2.1.17](https://defichain.com/downloads/). If syncing is stalled, try the `Reindex Option` via Settings, click on `Reindex after saving` followed by `delete peers and blocks`. Does your app sync? 

<img width="778" alt="Reindex   saving + delete peers and blocks" src="https://user-images.githubusercontent.com/65014479/108048639-3dcf7e80-7082-11eb-9758-3ebc49b3d73b.png">

![Reindex   saving + delete peers and blocks](https://user-images.githubusercontent.com/65014479/108048631-3a3bf780-7082-11eb-90b4-bb621c2af341.gif)

**Comment by MrStryker** [comment]
Is there a fix for this yet? My node syncs but it still says Sync disconnected.

**Comment by izzycsy** [comment]
Hi @MrStryker , we manage to reproduce this internally and the above solution worked, would appreciate if you can try the above solution and let me know the outcome. If it doesn't, kindly send your logs please. Thank you.

**Comment by MrStryker** [comment]
> Hi @MrStryker , we manage to reproduce this internally and the above solution worked, would appreciate if you can try the above solution and let me know the outcome. If it doesn't, kindly send your logs please. Thank you.

Does not work. I've tried it several times.  What log files do you need?

**Comment by MrStryker** [comment]
> Hi @MrStryker , we manage to reproduce this internally and the above solution worked, would appreciate if you can try the above solution and let me know the outcome. If it doesn't, kindly send your logs please. Thank you.

My issue was fixed.  My clock was manually adjusted on my PC.  When I put it to auto adjust the node was able to connect.

**Comment by izzycsy** [comment]
Hi @MrStryker , glad that your issue is fixed. Interesting so it was due to your time-clock on PC that's why you could not sync? What was your settings prior?

**Comment by izzycsy** [comment]
Hi @BenThrottle85 @kingsersch @TTSIP @thiencdam @goldi147 @jibesmaster @Ausafari @monnyfx @MrStryker , thank you for your patience on this issue. Update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
